In [1]:
#This notebook identifies relevant temperature information by cleaning and creating new dataframes so that trends in temperature during this 50 year period can be visualized and/or identified.
#This information is meant to be used in conjunction with other climate data to determine if and to what extent CO2 emsissions correlate with temperature changes in various geographical zones

In [3]:
# Include this line to make plots interactive
%matplotlib notebook
# Dependencies
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

hk_metadata_path = "../data/hk_cc_data.csv"

hk_data = pd.read_csv(hk_metadata_path)
hk_data

,mean_temp,Grass_Min_Temp,max_Temp,mean_amount_of_cloud,mean_dew_point_temp,mean_wet_bulb_temp,min_temp,pressure,rainfall,RH,date
0,17.7,12.4,20.7,32.0,13.4,15.2,15.5,1018.7,0,77.0,1970-01-01
1,19.5,12.8,22.9,44.0,14.1,16.4,17.2,1018.6,0,72.0,1970-01-02
2,18.8,14.7,21.2,35.0,13.3,15.7,17.5,1019.2,0,71.0,1970-01-03
3,17.9,13.8,20.7,20.0,13.1,15.2,16.1,1020.6,0,74.0,1970-01-04
4,14.7,13.1,18.2,66.0,7.4,11.1,11.8,1026.0,Trace,62.0,1970-01-05
...,...,...,...,...,...,...,...,...,...,...,...
18595,18.0,13.5,21.3,23.0,11.2,14.3,15.6,1020.3,0,65.0,2019-12-27
18596,18.5,14.9,20.9,64.0,13.1,15.4,16.8,1020.2,Trace,72.0,2019-12-28
18597,18.8,16.9,19.6,92.0,16.8,17.6,17.9,1018.3,9.3,88.0,2019-12-29
18598,20.3,18.7,22.5,90.0,18.7,19.3,18.8,1020.0,0.3,91.0,2019-12-30
18599,19.2,18.5,20.2,93.0,16.8,17.7,18.0,1024.9,Trace,86.0,2019-12-31

In [4]:
hk_data["date"]= pd.to_datetime(hk_data['date'].astype(str),format="%Y/%m/%d")
hk_data['YEAR'] = pd.DatetimeIndex(hk_data["date"]).year
hk_data['year']=pd.DatetimeIndex(hk_data["date"]).year

In [5]:
hk_data
#nl_data['YEAR'] = pd.DatetimeIndex(nl_data["DATE"]).year

,mean_temp,Grass_Min_Temp,max_Temp,mean_amount_of_cloud,mean_dew_point_temp,mean_wet_bulb_temp,min_temp,pressure,rainfall,RH,date,YEAR,year
0,17.7,12.4,20.7,32.0,13.4,15.2,15.5,1018.7,0,77.0,1970-01-01,1970.0,1970.0
1,19.5,12.8,22.9,44.0,14.1,16.4,17.2,1018.6,0,72.0,1970-01-02,1970.0,1970.0
2,18.8,14.7,21.2,35.0,13.3,15.7,17.5,1019.2,0,71.0,1970-01-03,1970.0,1970.0
3,17.9,13.8,20.7,20.0,13.1,15.2,16.1,1020.6,0,74.0,1970-01-04,1970.0,1970.0
4,14.7,13.1,18.2,66.0,7.4,11.1,11.8,1026.0,Trace,62.0,1970-01-05,1970.0,1970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18595,18.0,13.5,21.3,23.0,11.2,14.3,15.6,1020.3,0,65.0,2019-12-27,2019.0,2019.0
18596,18.5,14.9,20.9,64.0,13.1,15.4,16.8,1020.2,Trace,72.0,2019-12-28,2019.0,2019.0
18597,18.8,16.9,19.6,92.0,16.8,17.6,17.9,1018.3,9.3,88.0,2019-12-29,2019.0,2019.0
18598,20.3,18.7,22.5,90.0,18.7,19.3,18.8,1020.0,0.3,91.0,2019-12-30,2019.0,2019.0
18599,19.2,18.5,20.2,93.0,16.8,17.7,18.0,1024.9,Trace,86.0,2019-12-31,2019.0,2019.0

In [6]:
hk_data_df= hk_data.drop(columns=['Grass_Min_Temp','mean_amount_of_cloud','mean_dew_point_temp', 'mean_wet_bulb_temp', 'pressure','rainfall'])

In [7]:
#hk_data_df["24avg"]= mean_temp_list
#nl_data["MaxLow"] = max_low_list
#nl_data["MaxHigh"] = max_high_list
#school_data_complete["pass_math"]= pass_math
#school_data_complete["pass_read"]= pass_read
#school_data_complete.head()

hk_data.dropna()

,mean_temp,Grass_Min_Temp,max_Temp,mean_amount_of_cloud,mean_dew_point_temp,mean_wet_bulb_temp,min_temp,pressure,rainfall,RH,date,YEAR,year
0,17.7,12.4,20.7,32.0,13.4,15.2,15.5,1018.7,0,77.0,1970-01-01,1970.0,1970.0
1,19.5,12.8,22.9,44.0,14.1,16.4,17.2,1018.6,0,72.0,1970-01-02,1970.0,1970.0
2,18.8,14.7,21.2,35.0,13.3,15.7,17.5,1019.2,0,71.0,1970-01-03,1970.0,1970.0
3,17.9,13.8,20.7,20.0,13.1,15.2,16.1,1020.6,0,74.0,1970-01-04,1970.0,1970.0
4,14.7,13.1,18.2,66.0,7.4,11.1,11.8,1026.0,Trace,62.0,1970-01-05,1970.0,1970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18595,18.0,13.5,21.3,23.0,11.2,14.3,15.6,1020.3,0,65.0,2019-12-27,2019.0,2019.0
18596,18.5,14.9,20.9,64.0,13.1,15.4,16.8,1020.2,Trace,72.0,2019-12-28,2019.0,2019.0
18597,18.8,16.9,19.6,92.0,16.8,17.6,17.9,1018.3,9.3,88.0,2019-12-29,2019.0,2019.0
18598,20.3,18.7,22.5,90.0,18.7,19.3,18.8,1020.0,0.3,91.0,2019-12-30,2019.0,2019.0
18599,19.2,18.5,20.2,93.0,16.8,17.7,18.0,1024.9,Trace,86.0,2019-12-31,2019.0,2019.0

In [ ]:
hk_data_df

In [10]:
hk_data_grouped= hk_data_df.groupby(['YEAR']).mean()
hkdata = hk_data_grouped.round(decimals=2)
hkdata

        mean_temp  max_Temp  min_temp     RH    year
YEAR
1970.0      22.76     25.56     20.55  77.62  1970.0
1971.0      22.78     25.88     20.46  73.66  1971.0
1972.0      22.85     25.91     20.77  79.74  1972.0
1973.0      23.30     26.28     21.18  78.99  1973.0
1974.0      22.81     25.93     20.58  76.96  1974.0
1975.0      22.86     25.59     20.75  79.09  1975.0
1976.0      22.50     25.45     20.39  77.46  1976.0
1977.0      23.36     26.48     21.12  76.52  1977.0
1978.0      22.85     25.65     20.74  79.22  1978.0
1979.0      23.07     25.87     20.98  78.50  1979.0
1980.0      23.04     25.88     20.97  77.57  1980.0
1981.0      23.12     25.57     21.21  76.99  1981.0
1982.0      22.92     25.28     21.00  78.45  1982.0
1983.0      23.03     25.45     21.13  77.67  1983.0
1984.0      22.49     24.87     20.68  77.35  1984.0
1985.0      22.63     25.01     20.84  79.68  1985.0
1986.0      22.80     25.31     20.88  77.68  1986.0
1987.0      23.39     25.69     21.61  79.39  1987.0
1988.0      22.81     25.11     20.95  78.17  1988.0
1989.0      23.01     25.33     21.12  77.99  1989.0
1990.0      23.12     25.43     21.28  79.19  1990.0
1991.0      23.51     25.92     21.59  77.94  1991.0
1992.0      22.82     25.24     20.94  78.51  1992.0
1993.0      23.13     25.50     21.21  78.19  1993.0
1994.0      23.58     25.91     21.74  79.14  1994.0
1995.0      22.80     25.25     20.91  77.41  1995.0
1996.0      23.31     25.64     21.36  76.39  1996.0
1997.0      23.37     25.53     21.54  79.31  1997.0
1998.0      24.02     26.28     22.17  79.17  1998.0
1999.0      23.77     26.17     21.82  75.40  1999.0
2000.0      23.35     25.52     21.53  78.07  2000.0
2001.0      23.65     25.80     21.81  77.92  2001.0
2002.0      23.93     26.00     22.16  79.18  2002.0
2003.0      23.62     25.77     21.87  77.48  2003.0
2004.0      23.43     25.59     21.67  76.99  2004.0
2005.0      23.29     25.42     21.46  79.27  2005.0
2006.0      23.53     25.78     21.70  80.47  2006.0
2007.0      23.68     26.41     21.72  76.75  2007.0
2008.0      23.11     25.80     21.15  76.76  2008.0
2009.0      23.55     26.32     21.61  77.27  2009.0
2010.0      23.25     25.80     21.27  80.16  2010.0
2011.0      23.07     25.86     21.07  75.86  2011.0
2012.0      23.41     25.83     21.59  80.90  2012.0
2013.0      23.29     25.92     21.37  78.08  2013.0
2014.0      23.50     25.99     21.57  78.28  2014.0
2015.0      24.20     26.63     22.38  78.62  2015.0
2016.0      23.64     26.10     21.74  80.56  2016.0
2017.0      23.90     26.47     22.04  78.03  2017.0
2018.0      23.94     26.66     21.99  76.99  2018.0
2019.0      24.54     27.13     22.64  78.77  2019.0

In [11]:
#avg_list= year_sum["24avg"]
#type(avg_list)
#list_of_temps= avg_list.to_list()
#print(list_of_temps)

In [12]:


maxsum= hkdata["max_Temp"]
listofmax= maxsum.to_list()
print(listofmax)

[25.56, 25.88, 25.91, 26.28, 25.93, 25.59, 25.45, 26.48, 25.65, 25.87, 25.88, 25.57, 25.28, 25.45, 24.87, 25.01, 25.31, 25.69, 25.11, 25.33, 25.43, 25.92, 25.24, 25.5, 25.91, 25.25, 25.64, 25.53, 26.28, 26.17, 25.52, 25.8, 26.0, 25.77, 25.59, 25.42, 25.78, 26.41, 25.8, 26.32, 25.8, 25.86, 25.83, 25.92, 25.99, 26.63, 26.1, 26.47, 26.66, 27.13]

In [13]:
minsum= hkdata["min_temp"]
listofmin= minsum.to_list()
print(listofmin)

[20.55, 20.46, 20.77, 21.18, 20.58, 20.75, 20.39, 21.12, 20.74, 20.98, 20.97, 21.21, 21.0, 21.13, 20.68, 20.84, 20.88, 21.61, 20.95, 21.12, 21.28, 21.59, 20.94, 21.21, 21.74, 20.91, 21.36, 21.54, 22.17, 21.82, 21.53, 21.81, 22.16, 21.87, 21.67, 21.46, 21.7, 21.72, 21.15, 21.61, 21.27, 21.07, 21.59, 21.37, 21.57, 22.38, 21.74, 22.04, 21.99, 22.64]

In [14]:
meansum= hkdata["mean_temp"]
listofmean= meansum.to_list()
print(listofmean)

[22.76, 22.78, 22.85, 23.3, 22.81, 22.86, 22.5, 23.36, 22.85, 23.07, 23.04, 23.12, 22.92, 23.03, 22.49, 22.63, 22.8, 23.39, 22.81, 23.01, 23.12, 23.51, 22.82, 23.13, 23.58, 22.8, 23.31, 23.37, 24.02, 23.77, 23.35, 23.65, 23.93, 23.62, 23.43, 23.29, 23.53, 23.68, 23.11, 23.55, 23.25, 23.07, 23.41, 23.29, 23.5, 24.2, 23.64, 23.9, 23.94, 24.54]

In [15]:
sumofyears= hkdata["year"]
listofyears= sumofyears.to_list()
print(listofyears)

[1970.0, 1971.0, 1972.0, 1973.0, 1974.0, 1975.0, 1976.0, 1977.0, 1978.0, 1979.0, 1980.0, 1981.0, 1982.0, 1983.0, 1984.0, 1985.0, 1986.0, 1987.0, 1988.0, 1989.0, 1990.0, 1991.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0, 2017.0, 2018.0, 2019.0]

In [16]:

maxsum= hkdata["max_Temp"]
listofmax= maxsum.to_list()
minsum= hkdata["min_temp"]
listofmin= minsum.to_list()
meansum= hkdata["mean_temp"]
listofmean= meansum.to_list()
sumofyears= hkdata["year"]
listofyears= sumofyears.to_list()

In [17]:
    
# We will comment this out so you can run each section.
%matplotlib notebook

# Dependencies
#import matplotlib.pyplot as plt
#import numpy as np
#import pandas as pd

# Set x axis and tick locations
#x_axis = np.arange(len(hk_data_clean))
#tick_locations = [value for value in x_axis]

In [18]:
# Collect the mean unemployment rates for the world
#average_unemployment = combined_unemployed_data.mean()
#average_unemployment.head()

#2010    17.892957
#2011    17.902713
#2012    18.148142
#2013    18.100429
#2014    17.943539
print(listofmean)

[22.76, 22.78, 22.85, 23.3, 22.81, 22.86, 22.5, 23.36, 22.85, 23.07, 23.04, 23.12, 22.92, 23.03, 22.49, 22.63, 22.8, 23.39, 22.81, 23.01, 23.12, 23.51, 22.82, 23.13, 23.58, 22.8, 23.31, 23.37, 24.02, 23.77, 23.35, 23.65, 23.93, 23.62, 23.43, 23.29, 23.53, 23.68, 23.11, 23.55, 23.25, 23.07, 23.41, 23.29, 23.5, 24.2, 23.64, 23.9, 23.94, 24.54]

In [19]:
# Collect the years where data was collected
# this is getting the keys of the series (this will become our x-axis)
print(listofyears)
type(listofyears)

[1970.0, 1971.0, 1972.0, 1973.0, 1974.0, 1975.0, 1976.0, 1977.0, 1978.0, 1979.0, 1980.0, 1981.0, 1982.0, 1983.0, 1984.0, 1985.0, 1986.0, 1987.0, 1988.0, 1989.0, 1990.0, 1991.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0, 2017.0, 2018.0, 2019.0]

list

In [20]:
a= hkdata["mean_temp"] 
b= hkdata["max_Temp"] 
c= hkdata["min_temp"]
d= hkdata["year"]

In [21]:
hk_data

,mean_temp,Grass_Min_Temp,max_Temp,mean_amount_of_cloud,mean_dew_point_temp,mean_wet_bulb_temp,min_temp,pressure,rainfall,RH,date,YEAR,year
0,17.7,12.4,20.7,32.0,13.4,15.2,15.5,1018.7,0,77.0,1970-01-01,1970.0,1970.0
1,19.5,12.8,22.9,44.0,14.1,16.4,17.2,1018.6,0,72.0,1970-01-02,1970.0,1970.0
2,18.8,14.7,21.2,35.0,13.3,15.7,17.5,1019.2,0,71.0,1970-01-03,1970.0,1970.0
3,17.9,13.8,20.7,20.0,13.1,15.2,16.1,1020.6,0,74.0,1970-01-04,1970.0,1970.0
4,14.7,13.1,18.2,66.0,7.4,11.1,11.8,1026.0,Trace,62.0,1970-01-05,1970.0,1970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18595,18.0,13.5,21.3,23.0,11.2,14.3,15.6,1020.3,0,65.0,2019-12-27,2019.0,2019.0
18596,18.5,14.9,20.9,64.0,13.1,15.4,16.8,1020.2,Trace,72.0,2019-12-28,2019.0,2019.0
18597,18.8,16.9,19.6,92.0,16.8,17.6,17.9,1018.3,9.3,88.0,2019-12-29,2019.0,2019.0
18598,20.3,18.7,22.5,90.0,18.7,19.3,18.8,1020.0,0.3,91.0,2019-12-30,2019.0,2019.0
18599,19.2,18.5,20.2,93.0,16.8,17.7,18.0,1024.9,Trace,86.0,2019-12-31,2019.0,2019.0

In [23]:
# Plot the hong kong yearly temperature averages as a line chart in green
meanavg, = plt.plot(d, a, color="green", label="Mean Temp" )

#(min and max temps are here as place holders for comparison data)

# Plot the hong kong max temp average values in blue
#maxavg, = plt.plot(d, b, color="red",label='Max Avg')

# Plot the unemployment values for a single country
#minavg, = plt.plot(d, c, color="blue",label='Min Avg')


# Create a legend for our chart
plt.legend(handles=[meanavg, maxavg, minavg], loc="best")

# Add labels to the x and y axes
plt.title("Hong Kong Temperatures since 1970 (C)")
plt.xlabel("Years")
plt.ylabel("Degrees in Celsius")
plt.grid()

# Show the chart
plt.show()

NameError: name 'maxavg' is not defined

In [15]:
# Plot the hong kong yearly temperature averages as a line chart in green
meanavg, = plt.plot(d, a, color="green", label="Mean Temp" )

#(min and max temps are here as place holders for comparison data)

# Plot the hong kong max temp average values in blue
maxavg, = plt.plot(d, b, color="red",label='Max Avg')

# Plot the unemployment values for a single country
minavg, = plt.plot(d, c, color="blue",label='Min Avg')


# Create a legend for our chart
plt.legend(handles=[meanavg, maxavg, minavg], loc="best")

# Add labels to the x and y axes
plt.title("Hong Kong Temperatures since 1970 (C)")
plt.xlabel("Years")
plt.ylabel("Degrees in Celsius")
plt.grid()

# Show the chart
plt.show()

NameError: name 'd' is not defined